"""Seed 10 completed + 10 upcoming public events with distinct detail content."""
from datetime import date

from sqlalchemy import select

from app.models.event import Event
from app.utils.ids import generate_id

CATALOG_MARKER_SLUG = "european-health-informatics-congress-2024"


def _content(
    *,
    theme: str,
    overview_extra: str,
    topics: list[dict],
    speaker: dict,
    venue: dict,
    important_dates: list[dict],
    schedule: list[dict] | None = None,
    faq_extra: list[dict] | None = None,
) -> dict:
    schedule = schedule or [
        {"day": "Day 1", "time": "09:00", "session": "Opening ceremony & plenary", "speaker": speaker["full_name"]},
        {"day": "Day 2", "time": "10:30", "session": "Parallel research sessions", "speaker": "—"},
        {"day": "Day 3", "time": "14:00", "session": "Closing panel & awards", "speaker": "—"},
    ]
    faq = [
        {
            "question": "How do I submit my paper?",
            "answer": "Register in the applicant portal and complete the submission wizard for this event.",
        },
        {
            "question": "Is hybrid participation available?",
            "answer": "Yes — select your attendance format when applying.",
        },
    ]
    if faq_extra:
        faq.extend(faq_extra)

    return {
        "overview_markdown": (
            f"## About this event\n\n{theme}\n\n{overview_extra}\n\n"
            "### What to expect\n\n"
            "- Rigorous peer-oriented sessions\n"
            "- International delegate networking\n"
            "- Publication and certificate pathways"
        ),
        "important_dates": important_dates,
        "topics": topics,
        "people_groups": [
            {
                "group": "Keynote Speakers",
                "people": [speaker],
            }
        ],
        "submission": {
            "guidelines_markdown": (
                f"Submit through the ESC applicant portal. Follow the official template for **{theme.split('.')[0]}** tracks."
            ),
            "publication_markdown": "Accepted works may be included in conference proceedings subject to final academic approval.",
            "requirements": [
                "Original, unpublished research",
                "English-language manuscript",
                "Plagiarism screening required",
            ],
        },
        "schedule": schedule,
        "venue": venue,
        "quick_info": {
            "organizer": "Emerald Scholars Congress",
            "language": "English",
            "publication_type": "Conference Proceedings",
            "indexing": ["DOI-ready workflow", "Institutional repository deposit"],
            "certificates_available": True,
        },
        "faq": faq,
        "cta": {
            "title": "Ready to Submit Your Work?",
            "subtitle": "Create your account and apply for this event today.",
            "primary_label": "Apply Now",
            "primary_url": "/portal/signup",
        },
        "footer_cta": {
            "title": "Join the ESC Academic Community",
            "primary_label": "Apply Now",
            "primary_url": "/portal/signup",
        },
        "hero": {
            "primary_label": "Apply Now",
            "primary_url": "/portal/signup",
            "secondary_label": "Verify Certificate",
            "secondary_url": "/verify",
            "overlay_opacity": 0.52,
        },
    }


COMPLETED_EVENTS = [
    {
        "title": "European Health Informatics Congress 2024",
        "slug": "european-health-informatics-congress-2024",
        "event_code": "ESC-EVT-2024-HI",
        "subtitle": "Digital health, clinical data science & patient-centered systems",
        "event_type": "Congress",
        "category": "Health Informatics",
        "location": "Vienna, Austria",
        "country": "Austria",
        "format": "Hybrid",
        "start_date": date(2024, 4, 8),
        "end_date": date(2024, 4, 10),
        "submission_deadline": date(2024, 2, 15),
        "registration_deadline": date(2024, 3, 20),
        "status": "Completed",
        "short_description": "A leading European forum on digital health systems, EHR analytics, and clinical informatics.",
        "is_featured": True,
        "display_priority": 10,
        "content": _content(
            theme="Bridging clinical practice and data-driven health innovation across Europe.",
            overview_extra="Delegates explored telemedicine platforms, FHIR interoperability, and AI-assisted diagnostics.",
            topics=[
                {"title": "Clinical Data Science", "description": "EHR mining, cohort studies, and real-world evidence."},
                {"title": "Telehealth Systems", "description": "Remote care delivery and digital therapeutics."},
                {"title": "Medical AI Ethics", "description": "Governance for algorithmic decision support."},
            ],
            speaker={
                "full_name": "Prof. Anna Kowalski",
                "position": "Keynote Speaker",
                "institution": "Medical University of Vienna",
                "country": "Austria",
                "bio": "Specialist in health data standards and hospital digital transformation.",
            },
            venue={
                "venue_name": "Austria Center Vienna",
                "address": "Bruno-Kreisky-Platz 1",
                "city": "Vienna",
                "country": "Austria",
                "maps_url": "https://maps.google.com",
                "online_platform": "Microsoft Teams (hybrid)",
            },
            important_dates=[
                {"label": "Abstract deadline", "date": "2024-02-15"},
                {"label": "Conference dates", "date": "2024-04-08 – 2024-04-10"},
            ],
        ),
    },
    {
        "title": "Asia-Pacific Blockchain & FinTech Symposium 2024",
        "slug": "asia-pacific-blockchain-fintech-symposium-2024",
        "event_code": "ESC-EVT-2024-BC",
        "subtitle": "Distributed ledgers, digital assets & regulatory technology",
        "event_type": "Symposium",
        "category": "FinTech",
        "location": "Singapore",
        "country": "Singapore",
        "format": "In-person",
        "start_date": date(2024, 6, 3),
        "end_date": date(2024, 6, 5),
        "submission_deadline": date(2024, 4, 1),
        "registration_deadline": date(2024, 5, 15),
        "status": "Completed",
        "short_description": "Regional symposium on blockchain research, DeFi governance, and financial innovation.",
        "display_priority": 9,
        "content": _content(
            theme="Examining trustworthy financial infrastructure in the Asia-Pacific region.",
            overview_extra="Sessions covered CBDC pilots, smart-contract auditing, and cross-border settlement models.",
            topics=[
                {"title": "Blockchain Security", "description": "Consensus protocols and attack surfaces."},
                {"title": "RegTech", "description": "Compliance automation for digital finance."},
                {"title": "Token Economics", "description": "Incentive design and market integrity."},
            ],
            speaker={
                "full_name": "Dr. Mei Lin Tan",
                "position": "Keynote",
                "institution": "National University of Singapore",
                "country": "Singapore",
                "bio": "Research lead in decentralized systems and financial cryptography.",
            },
            venue={
                "venue_name": "Marina Bay Sands Expo",
                "address": "10 Bayfront Ave",
                "city": "Singapore",
                "country": "Singapore",
                "maps_url": "https://maps.google.com",
                "online_platform": "N/A (in-person)",
            },
            important_dates=[
                {"label": "Full paper deadline", "date": "2024-04-01"},
                {"label": "Symposium dates", "date": "2024-06-03 – 2024-06-05"},
            ],
        ),
    },
    {
        "title": "International Education Technology Summit 2024",
        "slug": "international-education-technology-summit-2024",
        "event_code": "ESC-EVT-2024-ED",
        "subtitle": "Learning sciences, LMS innovation & equitable access",
        "event_type": "Summit",
        "category": "Education",
        "location": "Toronto, Canada",
        "country": "Canada",
        "format": "Hybrid",
        "start_date": date(2024, 9, 12),
        "end_date": date(2024, 9, 14),
        "submission_deadline": date(2024, 7, 1),
        "registration_deadline": date(2024, 8, 20),
        "status": "Completed",
        "short_description": "Global summit on EdTech policy, adaptive learning, and classroom innovation.",
        "display_priority": 8,
        "content": _content(
            theme="Reimagining teaching and assessment in digitally connected classrooms.",
            overview_extra="Practitioners shared LMS analytics, micro-credential frameworks, and inclusive design.",
            topics=[
                {"title": "Adaptive Learning", "description": "Personalization engines and learning pathways."},
                {"title": "Assessment Design", "description": "Authentic evaluation in online environments."},
                {"title": "Equity in EdTech", "description": "Access gaps and policy interventions."},
            ],
            speaker={
                "full_name": "Prof. James Okafor",
                "position": "Summit Chair",
                "institution": "University of Toronto",
                "country": "Canada",
                "bio": "Scholar of learning analytics and higher-education innovation.",
            },
            venue={
                "venue_name": "Metro Toronto Convention Centre",
                "address": "255 Front St W",
                "city": "Toronto",
                "country": "Canada",
                "maps_url": "https://maps.google.com",
                "online_platform": "Zoom Events",
            },
            important_dates=[
                {"label": "Proposal deadline", "date": "2024-07-01"},
                {"label": "Summit dates", "date": "2024-09-12 – 2024-09-14"},
            ],
        ),
    },
    {
        "title": "Nordic Renewable Energy Conference 2024",
        "slug": "nordic-renewable-energy-conference-2024",
        "event_code": "ESC-EVT-2024-RE",
        "subtitle": "Wind, solar integration & grid modernization",
        "event_type": "Conference",
        "category": "Energy",
        "location": "Oslo, Norway",
        "country": "Norway",
        "format": "In-person",
        "start_date": date(2024, 10, 21),
        "end_date": date(2024, 10, 23),
        "submission_deadline": date(2024, 8, 10),
        "registration_deadline": date(2024, 9, 30),
        "status": "Completed",
        "short_description": "Nordic conference on clean energy systems, storage, and policy pathways.",
        "display_priority": 7,
        "content": _content(
            theme="Accelerating the transition to resilient low-carbon power networks.",
            overview_extra="Researchers presented offshore wind models, green hydrogen pilots, and grid flexibility studies.",
            topics=[
                {"title": "Offshore Wind", "description": "Turbine design and marine logistics."},
                {"title": "Energy Storage", "description": "Battery chemistry and grid-scale systems."},
                {"title": "Climate Policy", "description": "Carbon markets and national roadmaps."},
            ],
            speaker={
                "full_name": "Dr. Ingrid Solberg",
                "position": "Keynote Speaker",
                "institution": "NTNU Trondheim",
                "country": "Norway",
                "bio": "Expert in renewable integration and Nordic energy markets.",
            },
            venue={
                "venue_name": "Oslo Congress Centre",
                "address": "Youngs gate 21",
                "city": "Oslo",
                "country": "Norway",
                "maps_url": "https://maps.google.com",
                "online_platform": "N/A",
            },
            important_dates=[
                {"label": "Abstract submission", "date": "2024-08-10"},
                {"label": "Conference dates", "date": "2024-10-21 – 2024-10-23"},
            ],
        ),
    },
    {
        "title": "Latin American Urban Planning Forum 2024",
        "slug": "latin-american-urban-planning-forum-2024",
        "event_code": "ESC-EVT-2024-UP",
        "subtitle": "Smart cities, mobility & resilient infrastructure",
        "event_type": "Forum",
        "category": "Urban Studies",
        "location": "São Paulo, Brazil",
        "country": "Brazil",
        "format": "Hybrid",
        "start_date": date(2024, 11, 4),
        "end_date": date(2024, 11, 6),
        "submission_deadline": date(2024, 9, 1),
        "registration_deadline": date(2024, 10, 15),
        "status": "Completed",
        "short_description": "Forum on sustainable urban growth, transit-oriented design, and civic technology.",
        "display_priority": 6,
        "content": _content(
            theme="Designing inclusive cities for climate resilience and economic opportunity.",
            overview_extra="Case studies from São Paulo, Bogotá, and Mexico City informed mobility and housing debates.",
            topics=[
                {"title": "Smart Mobility", "description": "Transit data and multimodal planning."},
                {"title": "Affordable Housing", "description": "Land use and informal settlements."},
                {"title": "Urban Climate Adaptation", "description": "Heat islands and flood management."},
            ],
            speaker={
                "full_name": "Prof. Carla Mendes",
                "position": "Forum Chair",
                "institution": "University of São Paulo",
                "country": "Brazil",
                "bio": "Urban planner focused on Latin American megacity governance.",
            },
            venue={
                "venue_name": "Expo Center Norte",
                "address": "Rua José Bernardo Pinto 333",
                "city": "São Paulo",
                "country": "Brazil",
                "maps_url": "https://maps.google.com",
                "online_platform": "Webex Events",
            },
            important_dates=[
                {"label": "Extended abstract", "date": "2024-09-01"},
                {"label": "Forum dates", "date": "2024-11-04 – 2024-11-06"},
            ],
        ),
    },
    {
        "title": "Mediterranean Archaeology & Heritage Workshop 2025",
        "slug": "mediterranean-archaeology-heritage-workshop-2025",
        "event_code": "ESC-EVT-2025-AR",
        "subtitle": "Digital preservation, field methods & cultural policy",
        "event_type": "Workshop",
        "category": "Archaeology",
        "location": "Athens, Greece",
        "country": "Greece",
        "format": "In-person",
        "start_date": date(2025, 3, 17),
        "end_date": date(2025, 3, 19),
        "submission_deadline": date(2025, 1, 20),
        "registration_deadline": date(2025, 2, 28),
        "status": "Completed",
        "short_description": "Hands-on workshop on Mediterranean heritage documentation and conservation science.",
        "display_priority": 5,
        "content": _content(
            theme="Integrating field archaeology with digital heritage archives.",
            overview_extra="Participants reviewed LiDAR surveys, 3D reconstruction ethics, and museum digitization.",
            topics=[
                {"title": "Field Methods", "description": "Excavation recording and stratigraphy."},
                {"title": "Digital Heritage", "description": "Photogrammetry and open archives."},
                {"title": "Cultural Policy", "description": "UNESCO frameworks and community engagement."},
            ],
            speaker={
                "full_name": "Dr. Nikos Papadopoulos",
                "position": "Workshop Director",
                "institution": "National Archaeological Museum Athens",
                "country": "Greece",
                "bio": "Specialist in Aegean Bronze Age sites and heritage law.",
            },
            venue={
                "venue_name": "Megaron Athens International",
                "address": "Vassilissis Sofias Ave",
                "city": "Athens",
                "country": "Greece",
                "maps_url": "https://maps.google.com",
                "online_platform": "N/A",
            },
            important_dates=[
                {"label": "Workshop application", "date": "2025-01-20"},
                {"label": "Workshop dates", "date": "2025-03-17 – 2025-03-19"},
            ],
        ),
    },
    {
        "title": "World Materials Science Congress 2025",
        "slug": "world-materials-science-congress-2025",
        "event_code": "ESC-EVT-2025-MS",
        "subtitle": "Nanomaterials, composites & sustainable manufacturing",
        "event_type": "Congress",
        "category": "Materials Science",
        "location": "Seoul, South Korea",
        "country": "South Korea",
        "format": "Hybrid",
        "start_date": date(2025, 5, 6),
        "end_date": date(2025, 5, 9),
        "submission_deadline": date(2025, 3, 1),
        "registration_deadline": date(2025, 4, 20),
        "status": "Completed",
        "short_description": "International congress on advanced materials, characterization, and green manufacturing.",
        "display_priority": 4,
        "content": _content(
            theme="From lab-scale discovery to industrial materials deployment.",
            overview_extra="Highlights included graphene applications, battery materials, and circular production.",
            topics=[
                {"title": "Nanomaterials", "description": "Synthesis and toxicity assessment."},
                {"title": "Structural Composites", "description": "Aerospace and automotive applications."},
                {"title": "Green Manufacturing", "description": "Lifecycle analysis and recycling."},
            ],
            speaker={
                "full_name": "Prof. Hye-Jin Park",
                "position": "Congress President",
                "institution": "KAIST",
                "country": "South Korea",
                "bio": "Leading researcher in functional materials and energy devices.",
            },
            venue={
                "venue_name": "COEX Convention Center",
                "address": "513 Yeongdong-daero",
                "city": "Seoul",
                "country": "South Korea",
                "maps_url": "https://maps.google.com",
                "online_platform": "Hopin",
            },
            important_dates=[
                {"label": "Full paper deadline", "date": "2025-03-01"},
                {"label": "Congress dates", "date": "2025-05-06 – 2025-05-09"},
            ],
        ),
    },
    {
        "title": "UK Cybersecurity Research Conference 2025",
        "slug": "uk-cybersecurity-research-conference-2025",
        "event_code": "ESC-EVT-2025-CY",
        "subtitle": "Threat intelligence, zero trust & critical infrastructure",
        "event_type": "Conference",
        "category": "Cybersecurity",
        "location": "Manchester, United Kingdom",
        "country": "United Kingdom",
        "format": "Hybrid",
        "start_date": date(2025, 7, 14),
        "end_date": date(2025, 7, 16),
        "submission_deadline": date(2025, 5, 1),
        "registration_deadline": date(2025, 6, 20),
        "status": "Completed",
        "short_description": "UK-focused conference on offensive/defensive security research and national resilience.",
        "display_priority": 3,
        "content": _content(
            theme="Strengthening digital trust in public and private sector systems.",
            overview_extra="Talks addressed ransomware economics, supply-chain attacks, and post-quantum cryptography.",
            topics=[
                {"title": "Threat Intelligence", "description": "APT tracking and incident response."},
                {"title": "Zero Trust Architecture", "description": "Identity-centric network design."},
                {"title": "Critical Infrastructure", "description": "ICS/SCADA protection strategies."},
            ],
            speaker={
                "full_name": "Dr. Sarah Whitmore",
                "position": "Keynote",
                "institution": "University of Manchester",
                "country": "United Kingdom",
                "bio": "Cybersecurity scholar and UK NCSC research collaborator.",
            },
            venue={
                "venue_name": "Manchester Central",
                "address": "Windmill St",
                "city": "Manchester",
                "country": "United Kingdom",
                "maps_url": "https://maps.google.com",
                "online_platform": "Zoom Webinar",
            },
            important_dates=[
                {"label": "Paper submission", "date": "2025-05-01"},
                {"label": "Conference dates", "date": "2025-07-14 – 2025-07-16"},
            ],
        ),
    },
    {
        "title": "African Agricultural Innovation Summit 2025",
        "slug": "african-agricultural-innovation-summit-2025",
        "event_code": "ESC-EVT-2025-AG",
        "subtitle": "Food security, agri-tech & rural development",
        "event_type": "Summit",
        "category": "Agriculture",
        "location": "Nairobi, Kenya",
        "country": "Kenya",
        "format": "In-person",
        "start_date": date(2025, 9, 2),
        "end_date": date(2025, 9, 4),
        "submission_deadline": date(2025, 6, 15),
        "registration_deadline": date(2025, 8, 1),
        "status": "Completed",
        "short_description": "Continental summit on precision agriculture, soil health, and smallholder innovation.",
        "display_priority": 2,
        "content": _content(
            theme="Scaling science-based solutions for sustainable food systems across Africa.",
            overview_extra="Delegates discussed drought-resistant crops, mobile extension services, and cooperative finance.",
            topics=[
                {"title": "Precision Agriculture", "description": "Sensors, drones, and yield modeling."},
                {"title": "Soil Health", "description": "Regenerative practices and carbon sequestration."},
                {"title": "Rural Finance", "description": "Microcredit and value-chain access."},
            ],
            speaker={
                "full_name": "Prof. Amara Diallo",
                "position": "Summit Chair",
                "institution": "University of Nairobi",
                "country": "Kenya",
                "bio": "Agricultural economist specializing in East African food policy.",
            },
            venue={
                "venue_name": "KICC Nairobi",
                "address": "Harambee Ave",
                "city": "Nairobi",
                "country": "Kenya",
                "maps_url": "https://maps.google.com",
                "online_platform": "N/A",
            },
            important_dates=[
                {"label": "Abstract deadline", "date": "2025-06-15"},
                {"label": "Summit dates", "date": "2025-09-02 – 2025-09-04"},
            ],
        ),
    },
    {
        "title": "Pacific Marine Biology Symposium 2025",
        "slug": "pacific-marine-biology-symposium-2025",
        "event_code": "ESC-EVT-2025-MB",
        "subtitle": "Ocean conservation, fisheries & blue economy",
        "event_type": "Symposium",
        "category": "Marine Science",
        "location": "Sydney, Australia",
        "country": "Australia",
        "format": "Hybrid",
        "start_date": date(2025, 11, 10),
        "end_date": date(2025, 11, 12),
        "submission_deadline": date(2025, 9, 1),
        "registration_deadline": date(2025, 10, 20),
        "status": "Completed",
        "short_description": "Symposium on coral reef recovery, fisheries management, and marine biotechnology.",
        "display_priority": 1,
        "content": _content(
            theme="Protecting Pacific ecosystems while enabling responsible blue-economy growth.",
            overview_extra="Research tracks covered MPAs, ocean acidification, and sustainable aquaculture.",
            topics=[
                {"title": "Coral Reef Ecology", "description": "Bleaching resilience and restoration."},
                {"title": "Fisheries Management", "description": "Stock assessment and policy tools."},
                {"title": "Marine Biotechnology", "description": "Bioactive compounds from ocean organisms."},
            ],
            speaker={
                "full_name": "Dr. Liam Fraser",
                "position": "Symposium Chair",
                "institution": "University of Sydney",
                "country": "Australia",
                "bio": "Marine biologist focused on Southwest Pacific reef systems.",
            },
            venue={
                "venue_name": "ICC Sydney",
                "address": "14 Darling Dr",
                "city": "Sydney",
                "country": "Australia",
                "maps_url": "https://maps.google.com",
                "online_platform": "Teams Live",
            },
            important_dates=[
                {"label": "Submission deadline", "date": "2025-09-01"},
                {"label": "Symposium dates", "date": "2025-11-10 – 2025-11-12"},
            ],
        ),
    },
]

UPCOMING_EVENTS = [
    {
        "title": "International Conference on Quantum Computing 2026",
        "slug": "international-conference-quantum-computing-2026",
        "event_code": "ESC-EVT-2026-QC",
        "subtitle": "Algorithms, hardware & quantum-safe cryptography",
        "event_type": "Conference",
        "category": "Quantum Computing",
        "location": "Zurich, Switzerland",
        "country": "Switzerland",
        "format": "Hybrid",
        "start_date": date(2026, 7, 7),
        "end_date": date(2026, 7, 9),
        "submission_deadline": date(2026, 5, 1),
        "registration_deadline": date(2026, 6, 15),
        "status": "Submission Open",
        "short_description": "Premier conference on quantum algorithms, error correction, and industry pilots.",
        "is_featured": True,
        "display_priority": 20,
        "content": _content(
            theme="Exploring the next generation of computational paradigms and security implications.",
            overview_extra="Tracks include NISQ applications, topological qubits, and PQC migration planning.",
            topics=[
                {"title": "Quantum Algorithms", "description": "Optimization and simulation use cases."},
                {"title": "Hardware Platforms", "description": "Superconducting and trapped-ion systems."},
                {"title": "Post-Quantum Crypto", "description": "Standards and deployment roadmaps."},
            ],
            speaker={
                "full_name": "Prof. Markus Keller",
                "position": "Conference Chair",
                "institution": "ETH Zurich",
                "country": "Switzerland",
                "bio": "Quantum information researcher and industry liaison.",
            },
            venue={
                "venue_name": "Kongresshaus Zurich",
                "address": "Claridenstrasse 5",
                "city": "Zurich",
                "country": "Switzerland",
                "maps_url": "https://maps.google.com",
                "online_platform": "Zoom (hybrid)",
            },
            important_dates=[
                {"label": "Abstract submission", "date": "2026-05-01"},
                {"label": "Conference dates", "date": "2026-07-07 – 2026-07-09"},
            ],
        ),
    },
    {
        "title": "Global Climate Policy Forum 2026",
        "slug": "global-climate-policy-forum-2026",
        "event_code": "ESC-EVT-2026-CP",
        "subtitle": "Net-zero pathways, carbon markets & adaptation finance",
        "event_type": "Forum",
        "category": "Climate Policy",
        "location": "Copenhagen, Denmark",
        "country": "Denmark",
        "format": "Hybrid",
        "start_date": date(2026, 8, 18),
        "end_date": date(2026, 8, 20),
        "submission_deadline": date(2026, 6, 10),
        "registration_deadline": date(2026, 7, 25),
        "status": "Registration Open",
        "short_description": "Forum connecting researchers, policymakers, and NGOs on climate governance.",
        "display_priority": 19,
        "content": _content(
            theme="Translating climate science into actionable international policy frameworks.",
            overview_extra="Panels will address loss-and-damage funds, adaptation metrics, and just transition models.",
            topics=[
                {"title": "Net-Zero Planning", "description": "National inventories and sector roadmaps."},
                {"title": "Carbon Markets", "description": "Integrity, offsets, and Article 6 mechanisms."},
                {"title": "Adaptation Finance", "description": "Resilience investment in vulnerable regions."},
            ],
            speaker={
                "full_name": "Dr. Freja Lund",
                "position": "Forum Chair",
                "institution": "University of Copenhagen",
                "country": "Denmark",
                "bio": "Climate policy analyst and IPCC contributing author.",
            },
            venue={
                "venue_name": "Bella Center Copenhagen",
                "address": "Center Blvd 5",
                "city": "Copenhagen",
                "country": "Denmark",
                "maps_url": "https://maps.google.com",
                "online_platform": "Webex",
            },
            important_dates=[
                {"label": "Policy brief deadline", "date": "2026-06-10"},
                {"label": "Forum dates", "date": "2026-08-18 – 2026-08-20"},
            ],
        ),
    },
    {
        "title": "International Robotics & Automation Summit 2026",
        "slug": "international-robotics-automation-summit-2026",
        "event_code": "ESC-EVT-2026-RO",
        "subtitle": "Autonomous systems, human-robot collaboration & Industry 5.0",
        "event_type": "Summit",
        "category": "Robotics",
        "location": "Tokyo, Japan",
        "country": "Japan",
        "format": "In-person",
        "start_date": date(2026, 10, 5),
        "end_date": date(2026, 10, 7),
        "submission_deadline": date(2026, 8, 1),
        "registration_deadline": date(2026, 9, 15),
        "status": "Submission Open",
        "short_description": "Summit on industrial robots, soft robotics, and safe human-machine teaming.",
        "display_priority": 18,
        "content": _content(
            theme="Advancing dependable automation for manufacturing, healthcare, and logistics.",
            overview_extra="Demonstrations will include collaborative arms, warehouse AMRs, and surgical assist devices.",
            topics=[
                {"title": "Autonomous Navigation", "description": "SLAM, planning, and safety cases."},
                {"title": "Soft Robotics", "description": "Compliant actuators and grasping."},
                {"title": "Human-Robot Interaction", "description": "Trust, ergonomics, and standards."},
            ],
            speaker={
                "full_name": "Prof. Yuki Nakamura",
                "position": "Summit Chair",
                "institution": "University of Tokyo",
                "country": "Japan",
                "bio": "Roboticist specializing in manipulation and factory automation.",
            },
            venue={
                "venue_name": "Tokyo Big Sight",
                "address": "3 Chome-11-1 Ariake",
                "city": "Tokyo",
                "country": "Japan",
                "maps_url": "https://maps.google.com",
                "online_platform": "N/A",
            },
            important_dates=[
                {"label": "Paper deadline", "date": "2026-08-01"},
                {"label": "Summit dates", "date": "2026-10-05 – 2026-10-07"},
            ],
        ),
    },
    {
        "title": "European Biomedical Engineering Congress 2027",
        "slug": "european-biomedical-engineering-congress-2027",
        "event_code": "ESC-EVT-2027-BM",
        "subtitle": "Medical devices, imaging & regenerative therapies",
        "event_type": "Congress",
        "category": "Biomedical Engineering",
        "location": "Barcelona, Spain",
        "country": "Spain",
        "format": "Hybrid",
        "start_date": date(2027, 2, 16),
        "end_date": date(2027, 2, 18),
        "submission_deadline": date(2026, 12, 1),
        "registration_deadline": date(2027, 1, 20),
        "status": "Under Review",
        "short_description": "Congress on implant design, medical imaging AI, and tissue engineering breakthroughs.",
        "display_priority": 17,
        "content": _content(
            theme="Engineering solutions for next-generation diagnostics and therapy.",
            overview_extra="Sessions span MRI reconstruction, wearable biosensors, and regulatory science for devices.",
            topics=[
                {"title": "Medical Imaging", "description": "AI reconstruction and multimodal fusion."},
                {"title": "Implantable Devices", "description": "Biocompatibility and power systems."},
                {"title": "Regenerative Medicine", "description": "Scaffolds and stem-cell applications."},
            ],
            speaker={
                "full_name": "Dr. Lucia Ferrer",
                "position": "Congress President",
                "institution": "UPC Barcelona",
                "country": "Spain",
                "bio": "Biomedical engineer focused on cardiac device innovation.",
            },
            venue={
                "venue_name": "Fira Barcelona",
                "address": "Av. Joan Carles I 58",
                "city": "Barcelona",
                "country": "Spain",
                "maps_url": "https://maps.google.com",
                "online_platform": "Hopin",
            },
            important_dates=[
                {"label": "Full paper deadline", "date": "2026-12-01"},
                {"label": "Congress dates", "date": "2027-02-16 – 2027-02-18"},
            ],
        ),
    },
    {
        "title": "North American Data Science & Analytics Conference 2027",
        "slug": "north-american-data-science-analytics-conference-2027",
        "event_code": "ESC-EVT-2027-DS",
        "subtitle": "ML operations, responsible AI & enterprise analytics",
        "event_type": "Conference",
        "category": "Data Science",
        "location": "Chicago, USA",
        "country": "United States",
        "format": "Hybrid",
        "start_date": date(2027, 4, 13),
        "end_date": date(2027, 4, 15),
        "submission_deadline": date(2027, 2, 1),
        "registration_deadline": date(2027, 3, 20),
        "status": "Submission Open",
        "short_description": "Conference on scalable ML pipelines, fairness, and analytics in regulated industries.",
        "display_priority": 16,
        "content": _content(
            theme="Turning data assets into accountable, production-grade intelligence.",
            overview_extra="Industry tracks cover healthcare analytics, fraud detection, and generative AI governance.",
            topics=[
                {"title": "MLOps", "description": "Deployment, monitoring, and drift management."},
                {"title": "Responsible AI", "description": "Bias testing and explainability tooling."},
                {"title": "Enterprise Analytics", "description": "Dashboards, KPIs, and decision systems."},
            ],
            speaker={
                "full_name": "Prof. Michael Chen",
                "position": "Program Chair",
                "institution": "University of Chicago",
                "country": "United States",
                "bio": "Data scientist studying trustworthy machine learning at scale.",
            },
            venue={
                "venue_name": "McCormick Place",
                "address": "2301 S King Dr",
                "city": "Chicago",
                "country": "United States",
                "maps_url": "https://maps.google.com",
                "online_platform": "Zoom Events",
            },
            important_dates=[
                {"label": "Abstract deadline", "date": "2027-02-01"},
                {"label": "Conference dates", "date": "2027-04-13 – 2027-04-15"},
            ],
        ),
    },
    {
        "title": "International Space Research Symposium 2027",
        "slug": "international-space-research-symposium-2027",
        "event_code": "ESC-EVT-2027-SP",
        "subtitle": "Satellite systems, astrobiology & space policy",
        "event_type": "Symposium",
        "category": "Space Science",
        "location": "Houston, USA",
        "country": "United States",
        "format": "In-person",
        "start_date": date(2027, 6, 8),
        "end_date": date(2027, 6, 10),
        "submission_deadline": date(2027, 4, 1),
        "registration_deadline": date(2027, 5, 15),
        "status": "Open for Registration",
        "short_description": "Symposium on Earth observation missions, deep-space instrumentation, and commercial space law.",
        "display_priority": 15,
        "content": _content(
            theme="Expanding humanity's scientific reach through collaborative space programs.",
            overview_extra="Topics include CubeSat constellations, planetary protection, and lunar habitat research.",
            topics=[
                {"title": "Earth Observation", "description": "Remote sensing for climate monitoring."},
                {"title": "Astrobiology", "description": "Biosignature detection and mission design."},
                {"title": "Space Policy", "description": "Orbital debris and international treaties."},
            ],
            speaker={
                "full_name": "Dr. Rachel Kim",
                "position": "Symposium Chair",
                "institution": "NASA Johnson Space Center (affiliate)",
                "country": "United States",
                "bio": "Space systems engineer and policy advisor.",
            },
            venue={
                "venue_name": "George R. Brown Convention Center",
                "address": "1001 Avenida de las Americas",
                "city": "Houston",
                "country": "United States",
                "maps_url": "https://maps.google.com",
                "online_platform": "N/A",
            },
            important_dates=[
                {"label": "Paper submission", "date": "2027-04-01"},
                {"label": "Symposium dates", "date": "2027-06-08 – 2027-06-10"},
            ],
        ),
    },
    {
        "title": "Middle East Smart Infrastructure Forum 2027",
        "slug": "middle-east-smart-infrastructure-forum-2027",
        "event_code": "ESC-EVT-2027-IF",
        "subtitle": "Smart grids, water systems & digital twins",
        "event_type": "Forum",
        "category": "Infrastructure",
        "location": "Doha, Qatar",
        "country": "Qatar",
        "format": "Hybrid",
        "start_date": date(2027, 9, 21),
        "end_date": date(2027, 9, 23),
        "submission_deadline": date(2027, 7, 10),
        "registration_deadline": date(2027, 8, 30),
        "status": "Registration Open",
        "short_description": "Forum on intelligent infrastructure for arid regions and rapidly growing cities.",
        "display_priority": 14,
        "content": _content(
            theme="Building resilient utilities through IoT, AI, and systems engineering.",
            overview_extra="Case studies from the Gulf region highlight desalination, district cooling, and smart highways.",
            topics=[
                {"title": "Smart Water", "description": "Leak detection and demand forecasting."},
                {"title": "Digital Twins", "description": "City-scale simulation and maintenance."},
                {"title": "Energy Systems", "description": "Microgrids and solar integration."},
            ],
            speaker={
                "full_name": "Eng. Omar Al-Hassan",
                "position": "Forum Chair",
                "institution": "Qatar University",
                "country": "Qatar",
                "bio": "Civil engineer specializing in Gulf infrastructure modernization.",
            },
            venue={
                "venue_name": "Qatar National Convention Centre",
                "address": "Ar-Rayyan",
                "city": "Doha",
                "country": "Qatar",
                "maps_url": "https://maps.google.com",
                "online_platform": "Teams",
            },
            important_dates=[
                {"label": "Proposal deadline", "date": "2027-07-10"},
                {"label": "Forum dates", "date": "2027-09-21 – 2027-09-23"},
            ],
        ),
    },
    {
        "title": "Global Public Health & Epidemiology Webinar Series 2027",
        "slug": "global-public-health-epidemiology-webinar-2027",
        "event_code": "ESC-EVT-2027-PH",
        "subtitle": "Outbreak modeling, health equity & vaccination policy",
        "event_type": "Webinar",
        "category": "Public Health",
        "location": "Online",
        "country": "International",
        "format": "Online",
        "start_date": date(2027, 10, 12),
        "end_date": date(2027, 10, 14),
        "submission_deadline": date(2027, 8, 20),
        "registration_deadline": date(2027, 9, 30),
        "status": "Submission Open",
        "short_description": "Fully online series on epidemic forecasting, health systems, and global health governance.",
        "display_priority": 13,
        "content": _content(
            theme="Connecting epidemiologists and policymakers through accessible virtual sessions.",
            overview_extra="Live panels cover genomic surveillance, vaccine equity, and health workforce planning.",
            topics=[
                {"title": "Epidemic Modeling", "description": "SEIR variants and real-time dashboards."},
                {"title": "Health Equity", "description": "Access barriers and social determinants."},
                {"title": "Vaccination Policy", "description": "Coverage strategies and hesitancy research."},
            ],
            speaker={
                "full_name": "Dr. Priya Sharma",
                "position": "Series Director",
                "institution": "London School of Hygiene & Tropical Medicine",
                "country": "United Kingdom",
                "bio": "Epidemiologist focused on infectious disease surveillance.",
            },
            venue={
                "venue_name": "ESC Virtual Auditorium",
                "address": "Online — global access",
                "city": "Online",
                "country": "International",
                "maps_url": "",
                "online_platform": "ESC Live Stream",
            },
            important_dates=[
                {"label": "Abstract deadline", "date": "2027-08-20"},
                {"label": "Webinar dates", "date": "2027-10-12 – 2027-10-14"},
            ],
            faq_extra=[
                {
                    "question": "Do I need to travel?",
                    "answer": "No — this event is fully online with recorded sessions for registrants.",
                }
            ],
        ),
    },
    {
        "title": "Scandinavian Design & Innovation Workshop 2027",
        "slug": "scandinavian-design-innovation-workshop-2027",
        "event_code": "ESC-EVT-2027-DI",
        "subtitle": "Human-centered design, service innovation & sustainability",
        "event_type": "Workshop",
        "category": "Design",
        "location": "Stockholm, Sweden",
        "country": "Sweden",
        "format": "In-person",
        "start_date": date(2027, 11, 3),
        "end_date": date(2027, 11, 5),
        "submission_deadline": date(2027, 9, 1),
        "registration_deadline": date(2027, 10, 15),
        "status": "Submission Open",
        "short_description": "Intensive workshop on Nordic design thinking, prototyping, and circular product development.",
        "display_priority": 12,
        "content": _content(
            theme="Merging aesthetics, usability, and environmental responsibility in product design.",
            overview_extra="Studio sessions include rapid prototyping, user journey mapping, and lifecycle assessment.",
            topics=[
                {"title": "Service Design", "description": "Co-creation and journey orchestration."},
                {"title": "Circular Products", "description": "Materials selection and end-of-life planning."},
                {"title": "Design Research", "description": "Ethnography and evaluative studies."},
            ],
            speaker={
                "full_name": "Prof. Elsa Lindqvist",
                "position": "Workshop Lead",
                "institution": "Konstfack Stockholm",
                "country": "Sweden",
                "bio": "Designer-researcher in sustainable product ecosystems.",
            },
            venue={
                "venue_name": "Stockholm Waterfront Congress",
                "address": "Nils Ericsons Plan 4",
                "city": "Stockholm",
                "country": "Sweden",
                "maps_url": "https://maps.google.com",
                "online_platform": "N/A",
            },
            important_dates=[
                {"label": "Portfolio submission", "date": "2027-09-01"},
                {"label": "Workshop dates", "date": "2027-11-03 – 2027-11-05"},
            ],
        ),
    },
    {
        "title": "International Law & Digital Governance Summit 2027",
        "slug": "international-law-digital-governance-summit-2027",
        "event_code": "ESC-EVT-2027-LW",
        "subtitle": "AI regulation, data sovereignty & cross-border compliance",
        "event_type": "Summit",
        "category": "Law & Policy",
        "location": "Brussels, Belgium",
        "country": "Belgium",
        "format": "Hybrid",
        "start_date": date(2027, 12, 1),
        "end_date": date(2027, 12, 3),
        "submission_deadline": date(2027, 9, 20),
        "registration_deadline": date(2027, 11, 10),
        "status": "Submission Open",
        "short_description": "Summit on digital rights, AI acts, privacy law, and international regulatory harmonization.",
        "display_priority": 11,
        "content": _content(
            theme="Navigating legal frameworks for AI, platforms, and transnational data flows.",
            overview_extra="Panels compare EU, US, and Asia-Pacific approaches to accountability and enforcement.",
            topics=[
                {"title": "AI Regulation", "description": "Risk tiers, audits, and liability models."},
                {"title": "Data Sovereignty", "description": "Localization and cross-border transfers."},
                {"title": "Platform Governance", "description": "Content moderation and competition law."},
            ],
            speaker={
                "full_name": "Prof. Isabelle Dubois",
                "position": "Summit Chair",
                "institution": "Université libre de Bruxelles",
                "country": "Belgium",
                "bio": "Scholar of technology law and European digital policy.",
            },
            venue={
                "venue_name": "Square Brussels Meeting Centre",
                "address": "Mont des Arts",
                "city": "Brussels",
                "country": "Belgium",
                "maps_url": "https://maps.google.com",
                "online_platform": "Zoom (hybrid)",
            },
            important_dates=[
                {"label": "Paper deadline", "date": "2027-09-20"},
                {"label": "Summit dates", "date": "2027-12-01 – 2027-12-03"},
            ],
        ),
    },
]


def _event_from_spec(spec: dict) -> Event:
    content = spec.pop("content")
    is_featured = spec.pop("is_featured", False)
    display_priority = spec.pop("display_priority", 0)
    overview = spec.get("short_description", "")
    return Event(
        id=generate_id("evt_"),
        content_json=content,
        overview=overview,
        is_featured=is_featured,
        display_priority=display_priority,
        is_public=True,
        **spec,
    )


def ensure_events_catalog(db) -> None:
    if db.scalar(select(Event).where(Event.slug == CATALOG_MARKER_SLUG)):
        return

    created = 0
    for spec in COMPLETED_EVENTS + UPCOMING_EVENTS:
        if db.scalar(select(Event).where(Event.slug == spec["slug"])):
            continue
        data = dict(spec)
        db.add(_event_from_spec(data))
        created += 1

    db.commit()
    if created:
        print(f"Events catalog: created {created} events (completed + upcoming).")
